import unittest.mock

from nix_scribe.lib.option_block import SimpleOptionBlock
from nix_scribe.modules.networking.base import NetworkingMapper, NetworkingScanner

MOCK_HOSTS = """
127.0.0.1 localhost
::1 localhost
127.0.1.1 my-hostname
192.168.1.50 server.internal server
"""

MOCK_RESOLV_STATIC = """
nameserver 1.1.1.1
nameserver 8.8.8.8
search internal.net
domain internal.net
"""

MOCK_RESOLV_DYNAMIC = """
# Generated by NetworkManager
nameserver 192.168.1.1
"""

MOCK_TIMESYNCD = """
[Time]
NTP=0.nixos.pool.ntp.org 1.nixos.pool.ntp.org
"""


def test_networking_scanner():
    mock_context = unittest.mock.MagicMock()

    def path_exists_side_effect(path):
        return path in [
            "/etc/hostname",
            "/etc/hosts",
            "/etc/resolv.conf",
            "/proc/sys/net/ipv6/conf/all/disable_ipv6",
            "/etc/systemd/timesyncd.conf",
        ]

    def read_file_side_effect(path):
        if path == "/etc/hostname":
            return "my-hostname\n"
        if path == "/etc/hosts":
            return MOCK_HOSTS
        if path == "/etc/resolv.conf":
            return MOCK_RESOLV_STATIC
        if path == "/proc/sys/net/ipv6/conf/all/disable_ipv6":
            return "0\n"
        if path == "/etc/systemd/timesyncd.conf":
            return MOCK_TIMESYNCD
        return ""

    mock_context.path_exists.side_effect = path_exists_side_effect
    mock_context.read_file.side_effect = read_file_side_effect
    mock_context.systemctl.is_enabled.return_value = False

    scanner = NetworkingScanner()
    ir = scanner.scan(mock_context)

    assert ir["hostName"] == "my-hostname"
    assert ir["enableIpv6"] is True
    assert "192.168.1.50" in ir["hosts"]
    assert "server.internal" in ir["hosts"]["192.168.1.50"]
    assert "127.0.1.1" not in ir["hosts"]
    assert ir["nameservers"] == ["1.1.1.1", "8.8.8.8"]
    assert ir["search"] == ["internal.net"]
    assert ir["domain"] == "internal.net"
    assert ir["timeServers"] == ["0.nixos.pool.ntp.org", "1.nixos.pool.ntp.org"]


def test_networking_scanner_dynamic_resolv():
    mock_context = unittest.mock.MagicMock()
    mock_context.path_exists.return_value = True
    mock_context.read_file.side_effect = (
        lambda p: MOCK_RESOLV_DYNAMIC if p == "/etc/resolv.conf" else "1\n"
    )
    mock_context.systemctl.is_enabled.return_value = False

    scanner = NetworkingScanner()
    ir = scanner.scan(mock_context)

    # should be empty because it's dynamic
    assert ir["nameservers"] == []


def test_networking_mapper():
    mock_ir = {
        "hostName": "nixos-box",
        "enableIpv6": False,
        "hosts": {"10.0.0.1": ["gateway"]},
        "nameservers": ["1.1.1.1"],
        "useDHCP": True,
        "useNetworkd": True,
        "timeServers": ["pool.ntp.org"],
    }

    mapper = NetworkingMapper()
    block = mapper.map(mock_ir)

    assert isinstance(block, SimpleOptionBlock)
    data = block.data["networking"]
    assert data["hostName"] == "nixos-box"
    assert data["enableIpv6"] is False
    assert data["hosts"]["10.0.0.1"] == ["gateway"]
    assert data["nameservers"] == ["1.1.1.1"]
    assert data["useDHCP"] is True
    assert data["useNetworkd"] is True
    assert data["timeServers"] == ["pool.ntp.org"]
