from nix_scribe.lib.context import SystemContext
from nix_scribe.lib.option_block import SimpleOptionBlock
from nix_scribe.modules.networking.base import NetworkingMapper, NetworkingScanner

MOCK_HOSTS = """
127.0.0.1 localhost
::1 localhost
127.0.1.1 my-hostname
192.168.1.50 server.internal server
"""

MOCK_RESOLV_STATIC = """
nameserver 1.1.1.1
nameserver 8.8.8.8
search internal.net
domain internal.net
"""

MOCK_RESOLV_DYNAMIC = """
# Generated by NetworkManager
nameserver 192.168.1.1
"""

MOCK_TIMESYNCD = """
[Time]
NTP=0.nixos.pool.ntp.org 1.nixos.pool.ntp.org
"""


def test_networking_scanner(tmp_path, monkeypatch):
    (tmp_path / "etc").mkdir()
    (tmp_path / "etc/hostname").write_text("my-hostname\n")
    (tmp_path / "etc/hosts").write_text(MOCK_HOSTS)
    (tmp_path / "etc/resolv.conf").write_text(MOCK_RESOLV_STATIC)
    (tmp_path / "etc/systemd").mkdir()
    (tmp_path / "etc/systemd/timesyncd.conf").write_text(MOCK_TIMESYNCD)

    ipv6_path = tmp_path / "proc/sys/net/ipv6/conf/all"
    ipv6_path.mkdir(parents=True)
    (ipv6_path / "disable_ipv6").write_text("0\n")

    context = SystemContext(tmp_path)
    monkeypatch.setattr(context.systemctl, "is_enabled", lambda _: False)

    scanner = NetworkingScanner()
    ir = scanner.scan(context)

    assert ir["hostName"] == "my-hostname"
    assert ir["enableIpv6"] is True
    assert "192.168.1.50" in ir["hosts"]
    assert "server.internal" in ir["hosts"]["192.168.1.50"]
    assert "127.0.1.1" not in ir["hosts"]
    assert ir["nameservers"] == ["1.1.1.1", "8.8.8.8"]
    assert ir["search"] == ["internal.net"]
    assert ir["domain"] == "internal.net"
    assert ir["timeServers"] == ["0.nixos.pool.ntp.org", "1.nixos.pool.ntp.org"]


def test_networking_scanner_dynamic_resolv(tmp_path, monkeypatch):
    (tmp_path / "etc").mkdir()
    (tmp_path / "etc/resolv.conf").write_text(MOCK_RESOLV_DYNAMIC)

    context = SystemContext(tmp_path)
    monkeypatch.setattr(context.systemctl, "is_enabled", lambda _: False)

    scanner = NetworkingScanner()
    ir = scanner.scan(context)

    # should be empty because it's dynamic
    assert ir["nameservers"] == []


def test_networking_mapper():
    mock_ir = {
        "hostName": "nixos-box",
        "enableIpv6": False,
        "hosts": {"10.0.0.1": ["gateway"]},
        "nameservers": ["1.1.1.1"],
        "useDHCP": True,
        "useNetworkd": True,
        "timeServers": ["pool.ntp.org"],
    }

    mapper = NetworkingMapper()
    block = mapper.map(mock_ir)

    assert isinstance(block, SimpleOptionBlock)
    data = block.data["networking"]
    assert data["hostName"] == "nixos-box"
    assert data["enableIpv6"] is False
    assert data["hosts"]["10.0.0.1"] == ["gateway"]
    assert data["nameservers"] == ["1.1.1.1"]
    assert data["useDHCP"] is True
    assert data["useNetworkd"] is True
    assert data["timeServers"] == ["pool.ntp.org"]
