from typing import Any


def parse_hosts(content: str) -> dict[str, list[str]]:
    """
    Parses /etc/hosts file.
    Returns a dictionary mapping IP addresses to lists of hostnames.
    """
    hosts = {}
    for line in content.splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue

        parts = line.split()
        if len(parts) < 2:
            continue

        ip = parts[0]
        names = parts[1:]

        if ip not in hosts:
            hosts[ip] = []
        hosts[ip].extend(names)
    return hosts


def parse_resolv(content: str) -> dict[str, Any]:
    """
    Parses /etc/resolv.conf file.
    Returns a dictionary with nameservers, search, and domain.
    """
    result = {"nameservers": [], "search": [], "domain": None, "is_dynamic": False}

    dynamic_indicators = [
        "Generated by NetworkManager",
        "Generated by resolvconf",
        "systemd-resolved",
        "do not edit",
    ]
    if any(indicator in content for indicator in dynamic_indicators):
        result["is_dynamic"] = True

    for line in content.splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 2:
            continue

        key = parts[0]
        values = parts[1:]

        if key == "nameserver":
            result["nameservers"].extend(values)
        elif key == "search":
            result["search"].extend(values)
        elif key == "domain":
            result["domain"] = values[0]

    return result
