name: Bug report
description: Report a reproducible bug or regression
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short description of the problem
      placeholder: e.g. "Generates invalid Nix code."

  - type: textarea
    id: steps
    attributes:
      label: Describe the bug
      description: Describe the bug and how to reproduce it. Share logs.
    validations:
      required: true
