---
name: 💡 Core Feature Request
description: Improvements to the core infrastructure (CLI, Writer, Context, NixScribe).
title: '[Core]: '
labels: [component/core, kind/feature]
body:
  - type: input
    id: summary
    attributes:
      label: Problem Description
      description: What is missing or should be changed? (e.g., The CLI lacks robust
        dry-run logic.)
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should the architecture or code change to address this problem?
        Specify the files/classes that need modification.
    validations:
