import datetime
import logging
import os

from rich.console import Console
from rich.prompt import Confirm

from .arguments import args
from .lib.context import ElevationRequest, SystemContext
from .lib.nixfile import NixFile
from .modules.base import Module
from .modules.security import sudo

logger = logging.getLogger(__name__)


class NixScribe:
    def __init__(self, console: Console):
        self.context = SystemContext(args.input_path, use_sudo=os.geteuid() == 0)
        self.nix_file = NixFile("configuration", "Generated by nix-scribe")
        self.modules: list[Module] = [sudo.module]
        self.console = console

    def run(self):
        """
        Top level script.
        Scans, maps, and writes configuration.
        """
        logger.debug(datetime.datetime.now())
        logger.info("Starting nix-scribe system scan...")
        for mod in self.modules:
            self._scan_module(mod)

        logger.info(f"Finished system scan. {len(self.modules)} modules scanned.")

        logger.info("Mapping scanned data to nix option blocks...")
        for mod in self.modules:
            mod.run_map()
            if mod.option_block:
                self.nix_file.add_option_block(mod.option_block)

        logger.info("Finished mapping stage.")

        logger.info("Writing configuration...")
        self.nix_file.save(args.output_path)

        logger.info(f"Saved configuration to {args.output_path}")

    def _scan_module(self, mod: Module):
        """
        Runs a scanner, handling permission requests
        """
        while True:
            with self.console.status(
                status=f"[bold blue]Scanning {mod.name}[/]"
            ) as status:
                try:
                    mod.run_scan(self.context)
                    status.stop()
                    logger.info(f"Scanned [cyan]{mod.name}[/]")
                    break
                except ElevationRequest as e:
                    status.stop()
                    logger.warning(f"Permission denied: {e.description}")

                    if self.context.use_sudo:
                        logger.error(
                            "Sudo was attempted, but failed (authentication or access failure). Skipping."
                        )
                        return {}

                    if self._prompt_for_sudo():
                        if self.context.verify_sudo():
                            logger.info("[bold green]Sudo privileges acquired![/]")
                            continue
                        else:
                            logger.warning("Sudo authentication failed. Skipping.")
                            return {}
                    else:
                        logger.warning("Skipping this scanner.")
                        return {}
                except Exception as e:
                    status.stop()
                    logger.error(f"Failed scanning {mod.name}: {e}")
                    return {}

    def _prompt_for_sudo(self) -> bool:
        try:
            return Confirm.ask(
                "[bold yellow]Permission required.[/] Do you want to retry with sudo privileges?",
                console=self.console,
                default=True,
            )
        except EOFError:
            return False
