import os
import sys

from arguments import args
from lib.context import ElevationRequest, SystemContext
from lib.nixfile import NixFile
from modules.base import Module
from modules.security import sudo


class NixScribe:
    def __init__(self):
        self.context = SystemContext(use_sudo=os.geteuid() == 0)
        self.nix_file = NixFile("configuration", "Generated by NixScribe")
        self.modules: list[Module] = [sudo.module]

    def run(self):
        """
        Top level script.
        Scans, maps, and writes configuration.
        """
        print("Starting nix-scribe system scan...")

        for mod in self.modules:
            self._scan_module(mod)

        for mod in self.modules:
            mod.run_map()
            if mod.option_block:
                self.nix_file.add_option_block(mod.option_block)

        print("Generating Configuration...")
        self.nix_file.save(args.output_path)

    def _scan_module(self, mod: Module):
        """
        Runs a scanner, handling permission requests
        """

        while True:
            try:
                mod.run_scan(self.context)
                break
            except ElevationRequest as e:
                print(e)

                if self.context.use_sudo:
                    print("Sudo was attempted, but failed. Skipping.")
                    return {}

                if self._prompt_for_sudo():
                    if self.context.verify_sudo():
                        print("     + Sudo privileges acquired")
                        continue
                    else:
                        print("Sudo authentication failed. Skipping.")
                        return {}
                else:
                    print("Skipping this scanner.")
                    return {}
            except Exception as e:
                print(e)
                return {}

    def _prompt_for_sudo(self) -> bool:
        while True:
            response = (
                input("Do you want to retry with sudo privileges? [Y/n]")
                .lower()
                .strip()
            )
            if response in ["", "y", "yes"]:
                return True
            if response in ["n", "no"]:
                return False


if __name__ == "__main__":
    try:
        script = NixScribe()
        script.run()
    except KeyboardInterrupt:
        sys.exit(1)
